# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "my_new_project"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"
 
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Hook defining:
#on-run-start: ["truncate table dbt_raw.hooks.dbt_audits", "Insert into dbt_raw.hooks.dbt_audits (audit_type) values ('Logged in')"]
#on-run-end: "Insert into dbt_raw.hooks.dbt_audits (audit_type) values ('Logged out')"

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  my_var: "THEFT"
  chc_src_test: "src_chicagocrime"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      chicagocrime:
        chicagocrimedata:
          
          #          +pre-hook:
          #            ["truncate table dbt_raw.hooks.dbt_audits", "Insert into dbt_raw.hooks.dbt_audits (audit_type) values ('chicagocrime model pre-hook')"]
          materialized: table
#         database: demo
          database: '{{env_var("DBT_CHICAGOCRIME_DATABASE","demo")}}'
          schema: chic_crime
          tags:
            - crime
          tests:

      raw_zone:
        schema: raw_zone
        tags:
          - healthcare
          - health
#        post-hook:
#          - "INSERT INTO dbt_raw.hooks.dbt_audits (audit_type) VALUES ('healthcare folder post-hook');"

